# code: language=ansible
---
- name: Deploy API Development
  hosts: all
  become: true

  vars:
    internal_config:
      app:
        env: development
        port: 3001
        version: latest
        address: dev-api.konsulin.care
        base_url: dev-api.konsulin.care
        timezone: Asia/Jakarta
        endpoint_prefix: api
        reset_password_url: https://dev-api.konsulin.care/api/v1/auth/reset-password
        max_requests: 100
        shutdown_timeout_in_seconds: 30
        max_time_requests_per_seconds: 10
        request_body_limit_in_megabyte: 10
        account_deactivation_age_in_days: 30
        login_session_expired_time_in_hours: 24
        forgot_password_token_expired_time_in_minutes: 10
        minio_pre_signed_url_object_expiry_time_in_hours: 24
        questionnaire_guest_response_response_expired_time_in_minutes: 10
      fhir:
        base_url: https://fhir.konsulin.care/fhir
      jwt:
        secret: secret
        exp_time_in_hour: 24
      mailer:
        email_sender: mfardiansyah.id@gmail.com
      minio:
        profile_picture_max_upload_size_in_mb: 10
        bucket_name: konsulin-dev
      rabbitmq:
        mailer_queue: mailer
        whatsapp_queue: whatsapp
      mongodb:
        fhir_db_name: konsulin-dev
        konsulin_db_name: konsulin-dev
    driver_config:
      mongodb:
        port: 27017
        host: mongodb
        username: konsulin
        password: konsulin
      redis:
        host: redis
        port: 6379
        password: redisEPasswdxample
      logger:
        level: debug
        output_file_name: konsulin-dev.log
        output_error_file_name: konsulin-dev-error.log
      rabbitmq:
        port: 5672
        host: rabbitmq
        username: rabbitUser
        password: rabbitPasssword
      minio:
        port: 9000
        host: minio
        username: minioUserExample
        password: sample-password

  tasks:
    - name: Prepare application environment
      ansible.builtin.template:
        src: "templates/config.yaml.j2"
        dest: "{{ deployment_path }}/config/config.yaml"
