version: "2"
linters:
  default: none
  enable:
    - gocognit
    - goconst
    - dupl
    - govet
    - staticcheck
    - errcheck
    - gofumpt
  settings:
    gocognit:
      min-complexity: 20
    goconst:
      min-len: 3
      min-occurrences: 3
    dupl:
      threshold: 50
  exclusions:
    paths:
      - ".*_test\\.go$"
      - vendor
