internal_config:
  app:
    env: production
    port: "3000"
    version: v1
    address: localhost
    base_url: https://dev-api.konsulin.care/
    timezone: Asia/Jakarta
    endpoint_prefix: api
    reset_password_url: "https://dev-app.konsulin.care/reset-password-form?token="
    max_requests: 15
    shutdown_timeout_in_seconds: 3
    max_time_requests_per_seconds: 30
    request_body_limit_in_megabyte: 30
    account_deactivation_age_in_days: 30
    login_session_expired_time_in_hours: 2
    forgot_password_token_expired_time_in_minutes: 2

  fhir:
    base_url: https://fhir.konsulin.care/fhir/

  jwt:
    secret: 5r9OLzkYTaRzgP@DQtjG6ucp
    exp_time_in_hour: 1

  mailer:
    email_sender: funlab.ardihikaru@gmail.com

  minio:
    profile_picture_max_upload_size_in_mb: 2
    bucket_name: konsulin-dev

  rabbitmq:
    mailer_queue: dev.email
    whatsapp_queue: dev.whatsapp

  mongodb:
    fhir_db_name: spark
    konsulin_db_name: konsulin

driver_config:
  mongodb:
    port: "17017"
    host: 37.27.46.214
    username: konsulin
    password: QK5LypXa8XDHruiTQJBx

  redis:
    host: localhost
    port: "6379"
    password: customredis77

  logger:
    level: debug
    output_file_name: logger.log
    output_error_file_name: logger_error.log

  rabbitmq:
    port: "5672"
    host: 37.27.46.214
    username: konsulin
    password: va12mFaswaCOzM90Ed7K

  minio:
    port: "9001"
    host: minio.konsulin.care
    username: minioUserKonsln
    password: QbSZRmX9rWebFehKFioA
    use_ssl: false
