FROM golang:1.27 AS gobuild
LABEL maintainer="Muhammad Febrian Ardiansyah <mfardiansyah.id@gmail.com>"
LABEL stage=gobuild

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GO111MODULE=on

WORKDIR /go/src/github.com/konsulin-id/be-konsulin

# get current commit and create build number
# echoing only the first 7 chars of the GIT_COMMIT
RUN echo "$VERSION -> ${GIT_COMMIT}" > /go/src/github.com/konsulin-id/be-konsulin/BUILD.txt
COPY go.mod go.sum ./
COPY cmd ./cmd
COPY internal ./internal
COPY resources/rbac_model.conf resources/rbac_policy.csv ./resources/
COPY resources/fhir/CompartmentDefinition-patient.json resources/fhir/CompartmentDefinition-practitioner.json ./resources/fhir/
RUN go mod download
