package constvars

const (
	OyPaymentRoutingResource = "PaymentRouting"
)

const (
	OY_MOCK_ACCOUNT_NUMBER_SUCCESS              = "1234567890"
	OY_MOCK_ACCOUNT_NUMBER_FAILED               = "1234567891"
	OY_MOCK_ACCOUNT_NUMBER_FAILED_FORCE_CREDIT  = "1234567892"
	OY_MOCK_ACCOUNT_NUMBER_PENDING              = "1234567893"
	OY_MOCK_ACCOUNT_NUMBER_PENDING_FORCE_CREDIT = "1234567894"
)

const (
	OY_PAYMENT_CREATED_STATUS      = "CREATED"
	OY_WAITING_PAYMENT_STATUS      = "WAITING_PAYMENT"
	OY_PAYMENT_IN_PROGRESS_STATUS  = "PAYMENT_IN_PROGRESS"
	OY_DISBURSE_IN_PROGRESS_STATUS = "DISBURSE_IN_PROGRESS"
	OY_COMPLETE_STATUS             = "COMPLETE"
	OY_INCOMPLETE_STATUS           = "INCOMPLETE"
	OY_EXPIRED_STATUS              = "EXPIRED"
	OY_PAYMENT_FAILED_STATUS       = "PAYMENT_FAILED"
)
