package slot

import (
	"errors"
	"fmt"
	"konsulin-service/internal/pkg/constvars"
	"konsulin-service/internal/pkg/fhir_dto"
	"strconv"
	"strings"
	"time"
)

// ConvertAvailableTimeToWeeklyPlan maps FHIR AvailableTime entries to an internal weeklyPlan.
// It performs strict validation and fails fast on the first invalid entry. This ensures
// writer and reader remain consistent: if another feature wrote bad data, slot generation
// will stop early and surface the problem rather than silently diverge.
// This function is one of the must used function by other feature that relates
// to Slot generation to ensure consistency and correctness of the Slot generation.
func ConvertAvailableTimeToWeeklyPlan(avts []fhir_dto.AvailableTime) (weeklyPlan, error) {
	var wp weeklyPlan
	for i, a := range avts {
		if err := validateAndMapAvailableTime(i, a, &wp); err != nil {
			return weeklyPlan{}, err
		}
	}
	return wp, nil
}

// validateAndMapAvailableTime validates a single AvailableTime entry and adds it to the weekly plan.
func validateAndMapAvailableTime(i int, a fhir_dto.AvailableTime, wp *weeklyPlan) error {
	if a.AvailableStartTime == "" || a.AvailableEndTime == "" {
		return fmt.Errorf("availableTime[%d]: missing start/end time", i)
	}
	start, ok1 := parseClockFlex(a.AvailableStartTime)
	if !ok1 {
		return fmt.Errorf("availableTime[%d]: invalid start time '%s'", i, a.AvailableStartTime)
	}
	end, ok2 := parseClockFlex(a.AvailableEndTime)
	if !ok2 {
		return fmt.Errorf("availableTime[%d]: invalid end time '%s'", i, a.AvailableEndTime)
	}
	if !validWindow(start, end) {
		return fmt.Errorf("availableTime[%d]: start >= end (%02d:%02d >= %02d:%02d)", i, start.H, start.M, end.H, end.M)
	}
	if len(a.DaysOfWeek) == 0 {
		return fmt.Errorf("availableTime[%d]: empty daysOfWeek", i)
	}
	w := dayWindow{Start: start, End: end}
	hadDay := false
	for _, tok := range a.DaysOfWeek {
		mapped := mapDayToken(tok)
		if len(mapped) == 0 {
			return fmt.Errorf("availableTime[%d]: unknown day token '%s'", i, tok)
		}
		hadDay = true
		for _, wd := range mapped {
			appendWindow(wp, wd, w)
		}
	}
	if !hadDay {
		return errors.New("no valid days mapped")
	}
	return nil
}

func parseClockFlex(s string) (clock, bool) {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, ".", ":")
	parts := strings.Split(s, ":")
	if len(parts) < 2 {
		return clock{}, false
	}
	h, err1 := strconv.Atoi(parts[0])
	m, err2 := strconv.Atoi(parts[1])
	if err1 != nil || err2 != nil || h < 0 || h > 23 || m < 0 || m > 59 {
		return clock{}, false
	}
	return clock{H: h, M: m}, true
}

func validWindow(a, b clock) bool {
	return a.H*60+a.M < b.H*60+b.M
}

func mapDayToken(s string) []time.Weekday {
	t := strings.ToLower(strings.TrimSpace(s))
	switch t {
	case "mon", "monday":
		return []time.Weekday{time.Monday}
	case "tue", "tues", "tuesday":
		return []time.Weekday{time.Tuesday}
	case "wed", "wednesday":
		return []time.Weekday{time.Wednesday}
	case "thu", "thur", "thurs", "thursday":
		return []time.Weekday{time.Thursday}
	case "fri", "friday":
		return []time.Weekday{time.Friday}
	case "sat", "saturday":
		return []time.Weekday{time.Saturday}
	case "sun", "sunday":
		return []time.Weekday{time.Sunday}
	}
	return nil
}

func appendWindow(wp *weeklyPlan, wd time.Weekday, w dayWindow) {
	switch wd {
	case time.Monday:
		wp.Monday = append(wp.Monday, w)
	case time.Tuesday:
		wp.Tuesday = append(wp.Tuesday, w)
	case time.Wednesday:
		wp.Wednesday = append(wp.Wednesday, w)
	case time.Thursday:
		wp.Thursday = append(wp.Thursday, w)
	case time.Friday:
		wp.Friday = append(wp.Friday, w)
	case time.Saturday:
		wp.Saturday = append(wp.Saturday, w)
	case time.Sunday:
		wp.Sunday = append(wp.Sunday, w)
	}
}

func intervalKey(a, b time.Time) string {
	return a.UTC().Format(time.RFC3339) + "|" + b.UTC().Format(time.RFC3339)
}

// dayWorkIntervals converts day windows into continuous intervals on the given day and timezone.
func dayWorkIntervals(day time.Time, tz *time.Location, windows []dayWindow) []interval {
	if tz == nil {
		tz = time.Local
	}
	var out []interval
	for _, w := range windows {
		start := atClock(day, w.Start.H, w.Start.M, tz)
		end := atClock(day, w.End.H, w.End.M, tz)
		if end.After(start) {
			out = append(out, interval{Start: start, End: end})
		}
	}
	return out
}

// atClock returns the time on 'day' at hour:minute in the given timezone.
func atClock(day time.Time, h, m int, loc *time.Location) time.Time {
	d := day.In(loc)
	y, mo, dd := d.Date()
	return time.Date(y, mo, dd, h, m, 0, 0, loc)
}

// SlotTagSystemGenerated marks system-generated slots in meta.tag.code.
// Used by the payment flow when creating busy-unavailable overlap slots.
const SlotTagSystemGenerated = "system-generated"

// slotTagUserGenerated marks user-generated slots in meta.tag.code.
// This should only be used when a Slot is generated by the request of the user or
// is initated by user action, e.g when practitioner request unavailable time.
const slotTagUserGenerated = "user-generated"

// BuildSlotAdjustmentForAppointment computes the slot mutations needed when a new
// appointment is booked: it creates busy-unavailable overlap slots for the appointed
// window (cross-role blocking). Free slots are no longer generated by the backend;
// the frontend infers availability from non-free slots.
func BuildSlotAdjustmentForAppointment(
	practitionerRole fhir_dto.PractitionerRole,
	schedule fhir_dto.Schedule,
	existingSlots []fhir_dto.Slot,
	appointedStart, appointedEnd time.Time,
	appointedSlotID string,
	slotMinutes, bufferMinutes int,
) (toDelete []string, toCreate []fhir_dto.Slot, err error) {
	loc, tzErr := practitionerRole.GetPreferredTimezone()
	if tzErr != nil {
		return nil, nil, fmt.Errorf("failed to resolve timezone: %w", tzErr)
	}

	plan, planErr := ConvertAvailableTimeToWeeklyPlan(practitionerRole.AvailableTime)
	if planErr != nil {
		return nil, nil, fmt.Errorf("failed to convert available time to weekly plan: %w", planErr)
	}

	day := time.Date(appointedStart.In(loc).Year(), appointedStart.In(loc).Month(), appointedStart.In(loc).Day(), 0, 0, 0, 0, loc)

	windowsForDay := plan.forWeekday(day.Weekday())
	if len(windowsForDay) == 0 {
		// No configured windows for this day, nothing to adjust
		return nil, nil, nil
	}

	baseWindows := dayWorkIntervals(day, loc, windowsForDay)
	busySlots := buildBusyUnavailableOverlaps(appointedStart, appointedEnd, baseWindows, existingSlots, appointedSlotID, schedule.ID)
	return nil, busySlots, nil
}

// buildBusyUnavailableOverlaps creates busy-unavailable slots for appointment overlap with working windows.
func buildBusyUnavailableOverlaps(appointedStart, appointedEnd time.Time, baseWindows []interval, existingSlots []fhir_dto.Slot, appointedSlotID, scheduleID string) []fhir_dto.Slot {
	if !appointedStart.Before(appointedEnd) {
		return nil
	}
	overlaps := intersectIntervalsWithWindows(appointedStart, appointedEnd, baseWindows)

	existingIntervalToIDs := make(map[string][]string)
	for _, s := range existingSlots {
		k := intervalKey(s.Start, s.End)
		existingIntervalToIDs[k] = append(existingIntervalToIDs[k], s.ID)
	}

	var slots []fhir_dto.Slot
	for _, ov := range overlaps {
		k := intervalKey(ov.Start, ov.End)
		if ids, ok := existingIntervalToIDs[k]; ok {
			for _, id := range ids {
				if id != "" && id == appointedSlotID {
					// already exists, skip
					goto nextOverlap
				}
			}
		}
		slots = append(slots, fhir_dto.Slot{
			ResourceType: constvars.ResourceSlot,
			Schedule:     fhir_dto.Reference{Reference: constvars.FHIRRefPrefixSchedule + scheduleID, Type: "Schedule"},
			Status:       fhir_dto.SlotStatusBusyUnavailable,
			Start:        ov.Start,
			End:          ov.End,
		})
	nextOverlap:
	}
	return slots
}

func intersectIntervalsWithWindows(appStart, appEnd time.Time, windows []interval) []interval {
	var out []interval
	for _, w := range windows {
		s := w.Start
		if appStart.After(s) {
			s = appStart
		}
		e := w.End
		if appEnd.Before(e) {
			e = appEnd
		}
		if e.After(s) {
			out = append(out, interval{Start: s, End: e})
		}
	}
	return out
}
