package utils

import (
	"fmt"
	"net/url"
	"strings"
)

const redirectToPathMaxLength = 256

// ValidateRedirectPath checks that path is a safe internal relative path suitable
// for embedding in a magic link. It is the caller's responsibility to skip this call
// when path is empty (empty means "no redirect", which is valid).
//
// Rules enforced:
//   - Max 256 characters
//   - Must start with "/"
//   - Must not start with "//" (protocol-relative URL)
//   - Must not contain "://" (absolute URL with scheme)
//   - Must not contain null bytes
func ValidateRedirectPath(path string) error {
	if len(path) > redirectToPathMaxLength {
		return fmt.Errorf("redirectToPath exceeds maximum length of %d characters", redirectToPathMaxLength)
	}

	if strings.ContainsRune(path, '\x00') {
		return fmt.Errorf("redirectToPath contains invalid characters")
	}

	if strings.Contains(path, "://") {
		return fmt.Errorf("redirectToPath must not contain a URL scheme")
	}

	if !strings.HasPrefix(path, "/") {
		return fmt.Errorf("redirectToPath must be a relative path starting with /")
	}

	if strings.HasPrefix(path, "//") {
		return fmt.Errorf("redirectToPath must not use a protocol-relative URL")
	}

	return nil
}

// AppendRedirectToMagicLink appends redirectToPath as a query parameter to magicLink
// while preserving the URL fragment (the "#linkCode=..." portion generated by SuperTokens).
// The fragment must remain intact for the magic link to work.
//
// If redirectPath is empty, magicLink is returned unchanged.
func AppendRedirectToMagicLink(magicLink, redirectPath string) string {
	if redirectPath == "" {
		return magicLink
	}

	// Split on first '#' to isolate the fragment (SuperTokens link code)
	fragmentIdx := strings.Index(magicLink, "#")
	var base, fragment string
	if fragmentIdx == -1 {
		base = magicLink
	} else {
		base = magicLink[:fragmentIdx]
		fragment = magicLink[fragmentIdx:] // includes the '#'
	}

	// Append redirectToPath to the query string
	sep := "&"
	if !strings.Contains(base, "?") {
		sep = "?"
	}
	base += sep + "redirectToPath=" + url.QueryEscape(redirectPath)

	return base + fragment
}
