name: Deploy Trigger Coolify Workflow

on:
  workflow_call:
    secrets:
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_KEY:
        required: true
      COOLIFY_TRIGGER_URL:
        required: false
      COOLIFY_TOKEN:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Check Konsulin API Container Status 1
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Check Konsulin API Container Status..."
            docker ps -a | grep "konsulin-api" || echo "Container not found or SSH failed"

      - name: Trigger Coolify Deploy
        run: |
          if [ -n "${{ secrets.COOLIFY_TRIGGER_URL }}" ] && [ -n "${{ secrets.COOLIFY_TOKEN }}" ]; then
            echo "Triggering Coolify deployment..."
            curl "${{ secrets.COOLIFY_TRIGGER_URL }}" \
              --header "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}"
          else
            echo "Coolify secrets not provided. Skipping deployment trigger."
            exit 0
