name: Build and Release Development

on:
  workflow_dispatch:
  push:
    branches:
    - develop

jobs:
  docker:
    name: Containerization
    uses: ./.github/workflows/docker-self-hosted.yml
    with:
      TZ_ARG: Asia/Jakarta
      AUTHOR: ${{ github.actor }}
      VERSION: development
      GIT_COMMIT: ${{ github.sha }}
      RELEASE_TAG: $(git describe --tags --abbrev=0)
      RUN_NUMBER: ${{ github.run_number }}
      BUILD_TIME: $(date '+%Y-%m-%d_%H:%M:%S_%z')
      DOCKER_TAG: ${{ github.ref_name }}-${{ github.sha }}
      DOCKER_VENDOR_TAG: ${{ github.ref_name }}

  deploy:
    name: Deployment
    needs: [docker]
    uses: ./.github/workflows/deploy-ansible.yml
    with:
      DOCKER_TAG: ${{ github.ref_name }}-${{ github.sha }}
      ANSIBLE_PLAYBOOK: ./playbook-dev.yml
      ANSIBLE_INVENTORY_HOSTS: "37.27.46.214,"
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.DEVELOP_ANSIBLE_VAULT_PASSWORD }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
