name: CI/CD Workflow

on:
  push:
    branches:
      - develop
    tags:
      - "v*"

jobs:
  # Build and push Docker image
  docker:
    name: Build Docker Image
    uses: ./.github/workflows/docker-build.yml
    with:
      TZ_ARG: Asia/Jakarta
      AUTHOR: ${{ github.actor }}
      # Version control parameters
      VERSION: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'develop' }}
      TAG: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'develop' }}
      GIT_COMMIT: ${{ github.sha }}
      BUILD_TIME: ${{ github.event.head_commit.timestamp }}
      RUN_NUMBER: ${{ github.run_number }}
      # Environment flags
      IS_DEV: ${{ github.ref_name == 'develop' }}
      IS_PROD: ${{ startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  # Deploy to appropriate environment
  deploy:
    name: Deploy Application
    needs: docker
    if: ${{ github.ref_name == 'develop' || startsWith(github.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      COOLIFY_TRIGGER_URL: ${{ secrets.COOLIFY_TRIGGER_URL }}
      COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}

