name: Build and Release Production

on:
  release:
    types: [created]

jobs:
  docker:
    name: Containerization
    uses: ./.github/workflows/docker-self-hosted.yml
    with:
      TZ_ARG: Asia/Jakarta
      AUTHOR: ${{ github.actor }}
      VERSION: production
      GIT_COMMIT: ${{ github.sha }}
      RELEASE_TAG: ${{ github.event.release.tag_name }}
      RUN_NUMBER: ${{ github.run_number }}
      BUILD_TIME: $(date '+%Y-%m-%d_%H:%M:%S_%z')
      DOCKER_TAG: ${{ github.event.release.tag_name }}
      DOCKER_VENDOR_TAG: production

  deploy:
    name: Deployment
    needs: [docker]
    uses: ./.github/workflows/deploy-ansible.yml
    with:
      DOCKER_TAG: ${{ github.event.release.tag_name }}
      ANSIBLE_PLAYBOOK: playbook-prod.yml
      ANSIBLE_INVENTORY_HOSTS: "37.27.46.214,"
    secrets:
      ANSIBLE_VAULT_PASSWORD: ${{ secrets.PRODUCTION_ANSIBLE_VAULT_PASSWORD }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
