name: Triggering Coolify deployment

on:
  workflow_call:
    secrets:
      COOLIFY_URL:
        required: true
      COOLIFY_SERVICE:
        required: true
      COOLIFY_TOKEN:
        required: true

jobs:
  trigger-coolify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        env:
          COOLIFY_URL: ${{ secrets.COOLIFY_URL }}
          COOLIFY_SERVICE: ${{ secrets.COOLIFY_SERVICE }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
        run: |
          echo "Triggering Coolify deployment..."
          curl -X POST "$COOLIFY_URL/services/$COOLIFY_SERVICE/restart?latest=true" \
            --header "Authorization: Bearer $COOLIFY_TOKEN"
